
server:
  port: 8380

spring:
  application:
    name: demo-service
  jpa:
    hibernate:
      ddl-auto: update
    open-in-view: false
    database-platform: org.hibernate.dialect.PostgreSQLDialect
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect
        format_sql: true
        show_sql: true
  datasource:
    url: jdbc:postgresql://localhost:5432/Fen?currentSchema=demo&binaryTransfer=true&reWriteBatchedInserts=true&stringtype=unspecified
    username: fendriknicholas
    password: root
    driver-class-name: org.postgresql.Driver
    platform: postgres
    #schema: classpath:schema.sql
    initialization-mode: always
    hikari:
      maximum-pool-sie: 20
      connectionTimeout: 2000
      poolName: demo-hikari-postgres-cp
      maxLifetime: 1100000
      data-source-properties:
        cachePrepStmts: true
        prepStmtCacheSize: 250
        prepStmtCacheSqlLimit: 2048
        useServerPrepStmts: true
        useLocalSessionState: true
        rewriteBatchedStatements: true
        cacheResultSetMetadata: true
        cacheServerConfiguration: true
        elideSetAutoCommits: true
        maintainTimeStats: false